<a href="https://colab.research.google.com/github/aymenbe1-hub/Anal-tica-Web/blob/main/student_performance_plotly_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Análisis del Rendimiento del Alumno con Plotly Express

**Dataset:** [Student Performance – UCI Machine Learning Repository](https://archive.ics.uci.edu/dataset/320/student+performance)

**Objetivo:** Cargar, explorar y visualizar el dataset de rendimiento estudiantil usando `Plotly Express`.

---

## 1.  Instalación e Importación de Librerías

In [ ]:
# Instalamos plotly
!pip install plotly --quiet

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

print(' Librerías cargadas correctamente')

 Librerías cargadas correctamente

## 2.  Carga del Dataset

In [ ]:
# Cargamos el dataset directamente desde UCI
url = 'https://archive.ics.uci.edu/static/public/320/data.csv'
df = pd.read_csv(url)

print(f'Dataset cargado: {df.shape[0]} filas y {df.shape[1]} columnas')
df.head(10)

Dataset cargado: 649 filas y 33 columnas

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13
5,GP,M,16,U,LE3,T,4,3,services,other,...,5,4,2,1,2,5,6,12,12,13
6,GP,M,16,U,LE3,T,2,2,other,other,...,4,4,4,1,1,3,0,13,12,13
7,GP,F,17,U,GT3,A,4,4,other,teacher,...,4,1,4,1,1,1,2,10,13,13
8,GP,M,15,U,LE3,A,3,2,services,other,...,4,2,2,1,1,1,0,15,16,17
9,GP,M,15,U,GT3,T,3,4,other,other,...,5,5,1,1,1,5,0,12,12,13

## 3.  Exploración Inicial del Dataset

In [ ]:
# Información general del dataset
print('=== INFORMACIÓN GENERAL ===')
df.info()
print()
print('=== ESTADÍSTICAS DESCRIPTIVAS ===')
df.describe()

=== INFORMACIÓN GENERAL ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 649 entries, 0 to 648
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      649 non-null    object
 1   sex         649 non-null    object
 2   age         649 non-null    int64
 3   address     649 non-null    object
 4   famsize     649 non-null    object
 5   Pstatus     649 non-null    object
 6   Medu        649 non-null    int64
 7   Fedu        649 non-null    int64
 8   Mjob        649 non-null    object
 9   Fjob        649 non-null    object
 10  reason      649 non-null    object
 11  guardian    649 non-null    object
 12  traveltime  649 non-null    int64
 13  studytime   649 non-null    int64
 14  failures    649 non-null    int64
 15  schoolsup   649 non-null    object
 16  famsup      649 non-null    object
 17  paid        649 non-null    object
 18  activities  649 non-null    object
 19  nursery     649 non-null    object
 20  higher      649 non-null    object
 21  internet    649 non-null    object
 22  romantic    649 non-null    object
 23  famrel      649 non-null    int64
 24  freetime    649 non-null    int64
 25  goout       649 non-null    int64
 26  Dalc        649 non-null    int64
 27  Walc        649 non-null    int64
 28  health      649 non-null    int64
 29  absences    649 non-null    int64
 30  G1          649 non-null    int64
 31  G2          649 non-null    int64
 32  G3          649 non-null    int64
dtypes: int64(16), object(17)
memory usage: 167.4+ KB

=== ESTADÍSTICAS DESCRIPTIVAS ===

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000
mean,16.744222,2.514638,2.306626,1.568567,1.930663,0.221880,3.930663,3.180277,3.184900,1.502311,2.280431,3.536210,3.659476,11.399076,11.570108,11.906009
std,1.218138,1.134552,1.099931,0.748660,0.829510,0.593235,0.955717,1.051093,1.175766,0.924834,1.284380,1.446259,4.640759,2.745265,2.913639,3.230656
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,16.000000,2.000000,1.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,2.000000,0.000000,10.000000,10.000000,10.000000
50%,17.000000,2.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,2.000000,11.000000,11.000000,12.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,6.000000,13.000000,13.000000,14.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,32.000000,19.000000,19.000000,19.000000

In [ ]:
# Comprobamos valores nulos
print('=== VALORES NULOS ===')
print(df.isnull().sum())
print(f'\nTotal de valores nulos: {df.isnull().sum().sum()}')

=== VALORES NULOS ===
school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

Total de valores nulos: 0

In [ ]:
# Listamos todas las columnas disponibles
print('=== COLUMNAS DEL DATASET ===')
for i, col in enumerate(df.columns):
    print(f'{i+1:2}. {col}')

=== COLUMNAS DEL DATASET ===
 1. school
 2. sex
 3. age
 4. address
 5. famsize
 6. Pstatus
 7. Medu
 8. Fedu
 9. Mjob
10. Fjob
11. reason
12. guardian
13. traveltime
14. studytime
15. failures
16. schoolsup
17. famsup
18. paid
19. activities
20. nursery
21. higher
22. internet
23. romantic
24. famrel
25. freetime
26. goout
27. Dalc
28. Walc
29. health
30. absences
31. G1
32. G2
33. G3

## 4.  Preprocesamiento de Datos

In [ ]:
# Detectamos las columnas de notas finales
# Adaptamos según las columnas reales del CSV
print('Columnas disponibles:', df.columns.tolist())

# Seleccionamos columnas numéricas para análisis
num_cols = df.select_dtypes(include='number').columns.tolist()
cat_cols = df.select_dtypes(include='object').columns.tolist()

print(f'\nColumnas numéricas ({len(num_cols)}): {num_cols}')
print(f'Columnas categóricas ({len(cat_cols)}): {cat_cols}')

Columnas disponibles: ['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu', 'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime', 'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences', 'G1', 'G2', 'G3']

Columnas numéricas (16): ['age', 'Medu', 'Fedu', 'traveltime', 'studytime', 'failures', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences', 'G1', 'G2', 'G3']
Columnas categóricas (17): ['school', 'sex', 'address', 'famsize', 'Pstatus', 'Mjob', 'Fjob', 'reason', 'guardian', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'romantic']

In [ ]:
# Creamos columna de nota final si existe G3, o usamos la última nota numérica
if 'G3' in df.columns:
    df['nota_final'] = df['G3']
    print(' Usando columna G3 como nota final')
elif 'FinalGrade' in df.columns:
    df['nota_final'] = df['FinalGrade']
    print(' Usando columna FinalGrade como nota final')
else:
    # Usamos la última columna numérica
    df['nota_final'] = df[num_cols[-1]]
    print(f' Usando columna "{num_cols[-1]}" como nota final')

# Clasificación de rendimiento
def clasificar_rendimiento(nota):
    if nota >= 18: return 'Excelente'
    elif nota >= 14: return 'Bueno'
    elif nota >= 10: return 'Suficiente'
    else: return 'Insuficiente'

df['rendimiento'] = df['nota_final'].apply(clasificar_rendimiento)
print('\n=== Distribución de Rendimiento ===')
print(df['rendimiento'].value_counts())

 Usando columna G3 como nota final

=== Distribución de Rendimiento ===
rendimiento
Suficiente      355
Bueno           177
Insuficiente    100
Excelente        17
Name: count, dtype: int64

## 5. Visualizaciones con Plotly Express

---
### 5.1 Distribución de la Nota Final (Histograma)

In [ ]:
fig = px.histogram(
    df,
    x='nota_final',
    nbins=20,
    color='rendimiento',
    title=' Distribución de la Nota Final de los Alumnos',
    labels={'nota_final': 'Nota Final', 'count': 'Número de Alumnos'},
    color_discrete_map={
        'Excelente': '#2ecc71',
        'Bueno': '#3498db',
        'Suficiente': '#f39c12',
        'Insuficiente': '#e74c3c'
    },
    template='plotly_white'
)
fig.update_layout(bargap=0.1)
fig.show()

### 5.2 Distribución del Rendimiento (Gráfico de Tarta / Pie Chart)

In [ ]:
rend_counts = df['rendimiento'].value_counts().reset_index()
rend_counts.columns = ['Rendimiento', 'Cantidad']

fig = px.pie(
    rend_counts,
    values='Cantidad',
    names='Rendimiento',
    title=' Distribución del Rendimiento Académico',
    color='Rendimiento',
    color_discrete_map={
        'Excelente': '#2ecc71',
        'Bueno': '#3498db',
        'Suficiente': '#f39c12',
        'Insuficiente': '#e74c3c'
    },
    hole=0.35,
    template='plotly_white'
)
fig.update_traces(textinfo='percent+label')
fig.show()

### 5.3 Evolución de Notas G1 → G2 → G3 (si existen)

In [ ]:
if all(c in df.columns for c in ['G1', 'G2', 'G3']):
    # Calculamos medias por período
    medias = pd.DataFrame({
        'Periodo': ['G1 (1er Período)', 'G2 (2º Período)', 'G3 (Nota Final)'],
        'Media': [df['G1'].mean(), df['G2'].mean(), df['G3'].mean()]
    })

    fig = px.line(
        medias,
        x='Periodo',
        y='Media',
        title=' Evolución de la Nota Media a lo Largo del Curso',
        markers=True,
        labels={'Media': 'Nota Media', 'Periodo': 'Período Evaluativo'},
        template='plotly_white',
        line_shape='spline'
    )
    fig.update_traces(line_color='#3498db', marker_size=12, line_width=3)
    fig.update_layout(yaxis_range=[0, 20])
    fig.show()
else:
    print(' Las columnas G1, G2, G3 no están disponibles en este CSV.')

### 5.4 Relación entre Ausencias y Nota Final (Scatter Plot)

In [ ]:
absences_col = 'absences' if 'absences' in df.columns else None

if absences_col:
    fig = px.scatter(
        df,
        x=absences_col,
        y='nota_final',
        color='rendimiento',
        title=' Relación entre Ausencias y Nota Final',
        labels={absences_col: 'Número de Ausencias', 'nota_final': 'Nota Final'},
        color_discrete_map={
            'Excelente': '#2ecc71',
            'Bueno': '#3498db',
            'Suficiente': '#f39c12',
            'Insuficiente': '#e74c3c'
        },
        trendline='ols',
        template='plotly_white'
    )
    fig.show()
else:
    print(' Columna absences no encontrada. Columnas disponibles:', df.columns.tolist())

### 5.5 Nota Final según Nivel de Educación de los Padres (Box Plot)

In [ ]:
# Buscamos columna de educación del padre/madre
edu_col = None
for c in ['Medu', 'Fedu', 'Mjob', 'Fjob', 'ParentEduc']:
    if c in df.columns:
        edu_col = c
        break

if edu_col:
    fig = px.box(
        df,
        x=edu_col,
        y='nota_final',
        color=edu_col,
        title=f' Nota Final según "{edu_col}"',
        labels={edu_col: edu_col, 'nota_final': 'Nota Final'},
        template='plotly_white'
    )
    fig.show()
else:
    print(' No se encontró columna de educación de padres.')

### 5.6 Mapa de Calor – Correlación entre Variables Numéricas

In [ ]:
# Calculamos la matriz de correlación
corr = df[num_cols].corr().round(2)

fig = px.imshow(
    corr,
    text_auto=True,
    title=' Mapa de Calor – Correlación entre Variables Numéricas',
    color_continuous_scale='RdBu_r',
    aspect='auto',
    template='plotly_white'
)
fig.update_layout(height=600)
fig.show()

### 5.7 Nota Final por Sexo (Violin Plot)

In [ ]:
sex_col = 'sex' if 'sex' in df.columns else None

if sex_col:
    fig = px.violin(
        df,
        x=sex_col,
        y='nota_final',
        color=sex_col,
        box=True,
        points='all',
        title=' Distribución de la Nota Final por Sexo',
        labels={sex_col: 'Sexo', 'nota_final': 'Nota Final'},
        template='plotly_white'
    )
    fig.show()
else:
    print('⚠️ Columna sex no encontrada.')

### 5.8 Tiempo de Estudio vs. Nota Final (Bar Chart Agrupado)

In [ ]:
studytime_col = 'studytime' if 'studytime' in df.columns else None

if studytime_col:
    estudio_map = {1: '<2h', 2: '2–5h', 3: '5–10h', 4: '>10h'}
    df['estudio_label'] = df[studytime_col].map(estudio_map)

    estudio_media = df.groupby('estudio_label')['nota_final'].mean().reset_index()
    estudio_media.columns = ['Horas de Estudio', 'Nota Media']

    orden = ['<2h', '2–5h', '5–10h', '>10h']
    estudio_media['Horas de Estudio'] = pd.Categorical(estudio_media['Horas de Estudio'], categories=orden, ordered=True)
    estudio_media = estudio_media.sort_values('Horas de Estudio')

    fig = px.bar(
        estudio_media,
        x='Horas de Estudio',
        y='Nota Media',
        title=' Tiempo de Estudio Semanal vs. Nota Media Final',
        color='Nota Media',
        color_continuous_scale='Blues',
        text='Nota Media',
        template='plotly_white'
    )
    fig.update_traces(texttemplate='%{text:.2f}', textposition='outside')
    fig.update_layout(yaxis_range=[0, 20])
    fig.show()
else:
    print(' Columna studytime no encontrada.')

### 5.9 Scatter Matrix (Pairs Plot) de Variables Clave

In [ ]:
# Seleccionamos las columnas más relevantes que existan
cols_interes = [c for c in ['G1', 'G2', 'G3', 'absences', 'studytime', 'failures', 'nota_final'] if c in df.columns]

color_col = 'rendimiento' if 'rendimiento' in df.columns else None

fig = px.scatter_matrix(
    df,
    dimensions=cols_interes,
    color=color_col,
    title='Scatter Matrix – Variables de Rendimiento Académico',
    color_discrete_map={
        'Excelente': '#2ecc71',
        'Bueno': '#3498db',
        'Suficiente': '#f39c12',
        'Insuficiente': '#e74c3c'
    },
    template='plotly_white'
)
fig.update_traces(diagonal_visible=False, marker_size=3)
fig.update_layout(height=700)
fig.show()

## 6.  Conclusiones del Análisis

A continuación se resumen los principales hallazgos obtenidos del análisis del dataset de rendimiento estudiantil:

1. **Distribución de notas:** La mayoría de los alumnos obtienen notas en el rango medio, con pocos alumnos en los extremos (muy alto o suspenso).

2. **Evolución académica:** Las notas muestran una tendencia consistente entre los tres períodos evaluativos, lo que indica que el rendimiento de un alumno es relativamente estable.

3. **Ausencias:** Se observa una correlación negativa entre el número de ausencias y la nota final: a más faltas, menor rendimiento.

4. **Tiempo de estudio:** Los alumnos que dedican más horas semanales al estudio tienden a obtener mejores notas, confirmando la importancia del esfuerzo.

5. **Factor sexo:** No se aprecian diferencias significativas entre sexos, aunque existe ligera variabilidad en la distribución.

6. **Educación familiar:** El nivel educativo de los padres tiene cierta correlación positiva con el rendimiento del alumno.

---
*Análisis realizado con Python + Plotly Express · Dataset UCI Student Performance*